language: node_js
sudo: false
notifications:
  email:
  - lingjia@nongfenqi.com
node_js:
- 6.10.0
install:
- npm install
deploy:
  provider: npm
  email: lingjia@nongfenqi.com
  api_key: 'FFwxljhRvMUG5rhealrKLmR0scCdgR+E/A+baBG8ruo0EDYnxfmV0LIgNLY8jzft+U75R5iKWQTUMv5PBWAs8qO9Zz1H1/OM6Ir8IpREcszRAqGKI92p8yChEHefjhBCRaKz7FpLlyBaIxOfDSqGLcjN/+3XuQGTOWQOsGrnLrcUQDHdOXaohXaogyYuF3qmy2llObA3AsTob5GF1MPwa3d82knfoTt7sFIwijaQ+38lMtjrRDDA5uidWEg0dWIh8snEN2nE+fflUqTXHYyEEF6MNoBbGy0artwZ4mVQT2TAwOvqdnGBnx/+zp+FyhJnymKv62nmkIrzkuKlbcduJhtqt+fhd6HkcYReqpVLwqY9BNHE9RjsVizn6zAgAWFqHWKxvi5fbUkelxzSz8PHuCivqm/W629/+QK4Nzi1npvNQzvuGoSKN6GDNBV0jsVTUvz5xLyWjnIOsU+QJW4A/qy4ZarOZ9WvxhvxvyFPTtcxdLhUPA6W8GRNztHfcB9vU1SKMytVWqOBenW1lMLFGckln1T5IO7VD8KTXFcdOp4xxetboVvRkzyPHyvRHsZsHgPmS6rB2Rp6Z4e/cGtb6UsGaHpYibHrz23/6oQOXd4wj/DWbrnxjwjHvmSnj63iOinpRQM40XGwxkw/JYQi2tE4CQMxbkJMhyHlt8Ot1h8='
  on:
    tags: true
env:
  global:
  - secure: PT9W7WcVZompvlkOfHzzjJ71SUjeoy7yCJh76Hy7KKQdRLVSnlb+ohV1hbw24pWJyEb+6V0RNHxZE7T/f67GcPKzOvBMakbFtKizVmU+Pbz+XKl7gE6D4xwXMnGrQG2CCKmCGZ9JAUVkcHlgc+4rCaRFxmW/fCnfnKY5Fj4dHbeNETnmMgTxeFt0mqBRjGcS9WGbO1R98waP5s0b/SEAjbhIz5C1V+zih38MVhZC3IWYdgu21lGGk2frmzAPnZUfhkFb5XSVCJrBTBIhAZIxjOgltr0Tp3lJ/i3SmJGRErEoeAGnOyFhq4ogsn1ihKhz3RSjDMnCZks3hwtCMBwyMz1+OVcqzVrOunNZPUuh5AwBEuWIVMbojWq+byyE8CC2df5fmPisZFp8ZOEZ+VRYwumgra7y///4Nvqx3Y8IkkDGNzP5+JkWrNvNBkjqIhpJrtcE6rFm0gMKBnXq8a59RAurnOzFUbvH89thR405Nq+Lcm0+5BqRFBruY90hC31wBm5l6ewt/DQKmaShiyE0H62tjHE49fxhG/tYmCo5WzeEc0V87mnPGThY9QZ8SLBAzryEpUroGP/RVS+WYha/T2SipV3fc8GEGm/9IKF5BbJHc+tfAnNaqG8Z20MgD+Yvgw9TUfC6XfWIpLGMyhe3jvw+9fiYGfjXv5wRT1gaY7U=
  - secure: FFwxljhRvMUG5rhealrKLmR0scCdgR+E/A+baBG8ruo0EDYnxfmV0LIgNLY8jzft+U75R5iKWQTUMv5PBWAs8qO9Zz1H1/OM6Ir8IpREcszRAqGKI92p8yChEHefjhBCRaKz7FpLlyBaIxOfDSqGLcjN/+3XuQGTOWQOsGrnLrcUQDHdOXaohXaogyYuF3qmy2llObA3AsTob5GF1MPwa3d82knfoTt7sFIwijaQ+38lMtjrRDDA5uidWEg0dWIh8snEN2nE+fflUqTXHYyEEF6MNoBbGy0artwZ4mVQT2TAwOvqdnGBnx/+zp+FyhJnymKv62nmkIrzkuKlbcduJhtqt+fhd6HkcYReqpVLwqY9BNHE9RjsVizn6zAgAWFqHWKxvi5fbUkelxzSz8PHuCivqm/W629/+QK4Nzi1npvNQzvuGoSKN6GDNBV0jsVTUvz5xLyWjnIOsU+QJW4A/qy4ZarOZ9WvxhvxvyFPTtcxdLhUPA6W8GRNztHfcB9vU1SKMytVWqOBenW1lMLFGckln1T5IO7VD8KTXFcdOp4xxetboVvRkzyPHyvRHsZsHgPmS6rB2Rp6Z4e/cGtb6UsGaHpYibHrz23/6oQOXd4wj/DWbrnxjwjHvmSnj63iOinpRQM40XGwxkw/JYQi2tE4CQMxbkJMhyHlt8Ot1h8=
